#!/bin/bash

[[ ! -d /etc/VPSManager ]] && exit 0
[[ ! -d /etc/bot ]] && exit 0
source ShellBot.sh
api_bot=$1
id_admin=$2
[[ -z $api_bot ]] && exit 0
[[ -z $id_admin ]] && exit 0
[[ ! -e /usr/lib/licence ]] && exit 0
ativos='/etc/bot/lista_ativos'
suspensos='/etc/bot/lista_suspensos'
ShellBot.init --token "$api_bot" --monitor --return map --flush
ShellBot.username
fun_menu() {
    [[ "${message_from_id[$id]}" == "$id_admin" ]] && {
        local env_msg
        env_msg="<b>❖────────────────────────────❖</b>\n"
        env_msg+="<b>                            ❣️ SLEHIBOT ❣️</b>\n"
        env_msg+="<b>                ★彡 VPS MANAGER BOT 彡★</b>\n"
        env_msg+="<b>❖────────────────────────────❖</b>\n\n"
        env_msg+="<b>⚠️ <i>SELECT AN OPTION BELOW!</i></b>\n\n"
	ShellBot.sendMessage --chat_id ${message_chat_id[$id]} --text "$env_msg" \
            --reply_markup "$keyboard1" \
            --parse_mode html
        return 0
    }
    [[ -d /etc/bot/suspensos/${message_from_username} ]] && {
        ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
            --text "$(echo -e "🚫 YOU ARE SUSPENDED 🚫\n\nCONTACT THE ADMINISTRATOR")"
        return 0
    }
    if [[ "$(grep -w "${message_from_username}" $ativos | grep -wc 'revenda')" != '0' ]]; then
        local env_msg
        env_msg="<b>❖────────────────────────────❖</b>\n"
        env_msg+="<b>                            ❣️ SLEHIBOT ❣️</b>\n"
        env_msg+="<b>                ★彡 VPS MANAGER BOT 彡★</b>\n"
        env_msg+="<b>❖────────────────────────────❖</b>\n\n"
        env_msg+="<b>⚠️ <i>SELECT AN OPTION BELOW!</i></b>\n\n"
	ShellBot.sendMessage --chat_id ${message_chat_id[$id]} --text "$env_msg" \
            --reply_markup "$keyboard1" \
            --parse_mode html
        return 0
    elif [[ "$(grep -w "${message_from_username}" $ativos | grep -wc 'subrevenda')" != '0' ]]; then
        local env_msg
        env_msg="<b>❖────────────────────────────❖</b>\n"
        env_msg+="<b>                            ❣️ SLEHIBOT ❣️</b>\n"
        env_msg+="<b>                ★彡 VPS MANAGER BOT 彡★</b>\n"
        env_msg+="<b>❖────────────────────────────❖</b>\n\n"
        env_msg+="<b>⚠️ <i>SELECT AN OPTION BELOW!</i></b>\n\n"
	ShellBot.sendMessage --chat_id ${message_chat_id[$id]} --text "$env_msg" \
            --reply_markup "$keyboard1" \
            --parse_mode html
        return 0
    else
        ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
            --text "$(echo -e 🚫 ACCESS DENIED 🚫)"
        return 0
    fi
}

fun_ajuda() {
    [[ ${message_chat_id[$id]} == "" ]] && {
        id_chatuser="${callback_query_message_chat_id[$id]}"
        id_name="${callback_query_from_username}"
    } || {
        id_chatuser="${message_chat_id[$id]}"
        id_name="${message_from_username}"
    }
    if [[ "$id_chatuser" = "$id_admin" ]]; then
        local env_msg
        env_msg="<b>❖────────────────────────────❖</b>\n"
        env_msg+="<b>彡❣️ SLEHIBOT  VPS MANAGER BOT ❣️彡</b>\n"
        env_msg+="<b>❖──────────────────────────────❖</b>\n\n"
        env_msg+="⚠️ <b>Available Commands</b>\n\n"
        env_msg+="[<b>01</b>] /menu = Display menu\n"
        env_msg+="[<b>02</b>] /info = Display information\n"
        env_msg+="[<b>03</b>] /help = Information about options\n\n"
        env_msg+="⚠️ <b>Available Options</b>\n\n"
        env_msg+="• <u>CREATE TEST</u> = Create ssh test\n\n"
        env_msg+="• <u>OPTIMIZE</u> = Clear cache - ram\n\n"
        env_msg+="• <u>SPEEDTEST</u> = Connection test\n\n"
        nv_msg+="• <u>HELP</u> = Information about options\n\n\n"
        env_msg+="<b>❖──────────────────────────────❖</b>\n"
        env_msg+="<b>彡❤️🌟 LAKMAL SANDARU 🌟❤️彡</b>\n"
        env_msg+="<b>❖──────────────────────────────❖</b>\n\n"
        ShellBot.sendMessage --chat_id $id_chatuser \
            --text "$(echo -e $env_msg)" \
            --parse_mode html
	ShellBot.sendMessage --chat_id $id_chatuser \
            --text "$(echo -e ✅ All Tutorials , Updates : @slehiteam)"
        return 0
    elif [[ -d /etc/bot/suspensos/$id_name ]]; then
        ShellBot.sendMessage --chat_id $id_chatuser \
            --text "$(echo -e "🚫 YOU ARE SUSPENDED 🚫\n\nCONTACT THE ADMINISTRATOR")"
	ShellBot.sendSticker --chat_id $id_chatuser \
            --sticker "CAACAgEAAxkBAAEDbIdhrlBIJ-fUNJHXn-g352lK26WtBQACYgEAAgkeUEUw-f8AAZo7VDciBA"
        return 0
    elif [[ "$(grep -w "$id_name" $ativos | awk '{print $NF}')" == 'revenda' ]]; then
        local env_msg
        env_msg="<b>❖──────────────────────────────❖</b>\n"
        env_msg+="<b>彡❣️ SLEHIBOT  VPS MANAGER BOT ❣️彡</b>\n"
        env_msg+="<b>❖──────────────────────────────❖</b>\n\n"
        env_msg+="⚠️ <b>Available Commands</b>\n\n"
        env_msg+="<b>[01] /menu</b> = Display menu\n"
        env_msg+="<b>[02] /info</b> = Display information\n"
        env_msg+="<b>[03] /help</b> = Information about options\n\n"
        env_msg+="⚠️ <b>Available Options</b>\n\n"
        env_msg+="• <u>CREATE TEST</u> = Create ssh test\n\n"
        env_msg+="• <u>HELP</u> = Information about options\n\n"
        env_msg+="<b>❖──────────────────────────────❖</b>\n"
        env_msg+="<b>彡❤️🌟 LAKMAL SANDARU 🌟❤️彡</b>\n"
        env_msg+="<b>❖──────────────────────────────❖</b>\n\n"
        ShellBot.sendMessage --chat_id $id_chatuser \
            --text "$(echo -e $env_msg)" \
            --parse_mode html
	ShellBot.sendMessage --chat_id $id_chatuser \
            --text "$(echo -e ✅ All Tutorials , Updates : @slehiteam)"
        return 0
    elif [[ "$(grep -w "$id_name" $ativos | awk '{print $NF}')" == 'subrevenda' ]]; then
        local env_msg
        env_msg="<b>❖──────────────────────────────❖</b>\n"
        env_msg+="<b>                               ❣️ SLEHIBOT ❣️</b>\n"
        env_msg+="<b>                   ★彡 VPS MANAGER BOT 彡★</b>\n"
        env_msg+="<b>❖──────────────────────────────❖</b>\n\n"
        env_msg+="⚠️ <b>Available Commands</b>\n\n"
        env_msg+="[<b>01</b>] /menu = display menu\n"
        env_msg+="[<b>02</b>] /info = Display information\n"
        env_msg+="[<b>03</b>] /help = Information about options\n\n"
        env_msg+="⚠️ <b>Available Options</b>\n\n"
        env_msg+="• <u>CREATE TEST</u> = Create ssh test\n\n"
        env_msg+="• <u>HELP</u> = Information about options\n\n"
        ShellBot.sendMessage --chat_id $id_chatuser \
            --text "$(echo -e $env_msg)" \
            --parse_mode html
	ShellBot.sendMessage --chat_id $id_chatuser \
            --text "✅ All Tutorials , Updates : @slehiteam"
        return 0
    else
        ShellBot.sendMessage --chat_id $id_chatuser \
            --text "$(echo -e 🚫 ACCESS DENIED 🚫)"
	ShellBot.sendSticker --chat_id $id_chatuser \
            --sticker "CAACAgEAAxkBAAEDbIdhrlBIJ-fUNJHXn-g352lK26WtBQACYgEAAgkeUEUw-f8AAZo7VDciBA"
        return 0
    fi
}

verifica_acesso() {
    [[ "${message_from_id[$id]}" != "$id_admin" ]] && {
        [[ "$(grep -wc ${message_from_username} $suspensos)" != '0' ]] || [[ "$(grep -wc ${message_from_username} $ativos)" == '0' ]] && {
            _erro="1"
            return 0
        }
    }
}

otimizer() {
    [[ "${callback_query_from_id[$id]}" != "$id_admin" ]] && {
        ShellBot.sendMessage --chat_id ${callback_query_message_chat_id[$id]} \
            --text "$(echo -e 🚫 ACCESS DENIED 🚫)"
        return 0
    }
    MEM1=$(free | awk '/Mem:/ {print int(100*$3/$2)}')
    ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
        --text "🧹 LEARING SERVER CACHE"
    apt-get autoclean -y
    echo 3 >/proc/sys/vm/drop_caches
    sync && sysctl -w vm.drop_caches=3 1>/dev/null 2>/dev/null
    sysctl -w vm.drop_caches=0 1>/dev/null 2>/dev/null
    swapoff -a
    swapon -a
    ram1=$(free -h | grep -i mem | awk {'print $2'})
    ram2=$(free -h | grep -i mem | awk {'print $3'})
    ram3=$(free -h | grep -i mem | awk {'print $4'})
    MEM2=$(free | awk '/Mem:/ {print int(100*$3/$2)}')
    res=$(expr $MEM1 - $MEM2)
    local sucess
    sucess="❖──────────────────❖\n"
    sucess+="<b>  SUCCESSFULLY OPTIMIZED!</b>\n"
    sucess+="❖──────────────────❖\n\n"
    sucess+="<i>Previous use</i> $MEM1%\n\n"
    sucess+="<b>Total Ram Memory</b> $ram1\n"
    sucess+="<b>free</b> $ram3\n"
    sucess+="<b>In use</b> $ram2\n"
    sucess+="<i>current use</i> $MEM2%\n\n"
    sucess+="<b>Saving:</b> $res%"
    ShellBot.sendMessage --chat_id $id_admin \
        --text "$(echo -e $sucess)" \
        --parse_mode html
    return 0
}

speed_test() {
    [[ "${callback_query_from_id[$id]}" != "$id_admin" ]] && {
        ShellBot.sendMessage --chat_id ${callback_query_message_chat_id[$id]} \
            --text "$(echo -e 🚫 ACCESS DENIED 🚫)"
        return 0
    }
    rm -rf $HOME/speed >/dev/null 2>&1
    ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
        --text "🚀 TESTING SERVER SPEED"
    speedtest --share >speed
    png=$(cat speed | sed -n '5 p' | awk -F : {'print $NF'})
    down=$(cat speed | sed -n '7 p' | awk -F : {'print $NF'})
    upl=$(cat speed | sed -n '9 p' | awk -F : {'print $NF'})
    lnk=$(cat speed | sed -n '10 p' | awk {'print $NF'})
    local msg
    msg="❖──────────────────❖\n"
    msg+="<b> --⟫⟫⟫🚀 SERVER SPEED 🚀⟪⟪⟪—</b>\n"
    msg+="❖──────────────────❖\n\n"
    msg+="<b>PING/LATENCY:</b>$png\n"
    msg+="<b>DOWNLOAD:</b>$down\n"
    msg+="<b>UPLOAD:</b>$upl\n"
    ShellBot.sendMessage --chat_id $id_admin \
        --text "$(echo -e $msg)" \
        --parse_mode html
    ShellBot.sendMessage --chat_id $id_admin \
        --text "$(echo -e $lnk)" \
        --parse_mode html
    rm -rf $HOME/speed >/dev/null 2>&1
    return 0
}

sobremim() {
    local msg
    msg="❖──────────────────❖\n"
    msg+="<b>❣️ SLEHIBOT VPS MANAGER ❣️</b>\n"
    msg+="❖──────────────────❖\n\n"
    msg+="<b>Developed by:</b> @slehiteam\n"
    msg+="<b>Official Group:</b> @slehibot\n\n"
    msg+="I was created with the purpose of providing information and tools for VPN management on 🐧 GNU/Linux 🐧 servers.\n\n"
    msg+="<b>Menu:</b> /menu\n"
    ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
        --text "$(echo -e $msg)" \
        --parse_mode html
    return 0
}

fun_add_teste() {
    if [[ "$(grep -wc ${callback_query_from_username} $suspensos)" != '0' ]]; then
        ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
            --text "⚠️ YOU ARE SUSPENDED! CONTACT THE ADMINISTRATOR"
        return 0
    elif [[ "${callback_query_from_id[$id]}" == "$id_admin" ]]; then
        ShellBot.sendMessage --chat_id ${callback_query_message_chat_id[$id]} \
            --text "🙎‍♂️ CREATE TEST SSH 🙎‍♂️\n\nHow Many Hours Should It Last EX: 1:" \
            --reply_markup "$(ShellBot.ForceReply)"
    elif [[ "$(grep -wc ${callback_query_from_username} $ativos)" != '0' ]]; then
        _limTotal=$(grep -w "${callback_query_from_username}" $ativos | awk '{print $4}')
        fun_verif_limite_rev ${callback_query_from_username}
        _limsomarev2=$(echo "$_result + 1" | bc)
        [[ "$_limsomarev2" -gt "$_limTotal" ]] && {
            ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
                --text "❌ You have NO LIMIT AVAILABLE!"
            return 0
        } || {
            ShellBot.sendMessage --chat_id ${callback_query_message_chat_id[$id]} \
                --text "🙎‍♂️ CREATE TEST SSH 🙎‍♂️\n\nHow Many Hours Should It Last EX: 1:" \
                --reply_markup "$(ShellBot.ForceReply)"
        }
    else
        ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
            --text "🚫 ACCESS DENIED 🚫"
        return 0
    fi
}

fun_teste() {
    usuario=$(echo SLEHI$((RANDOM % +500)))
    senha='slehibot'
    limite='2'
    t_time=$1
    ex_date=$(date '+%d/%m/%C%y' -d " +2 days")
    tuserdate=$(date '+%C%y/%m/%d' -d " +2 days")
    [[ -z $t_time ]] && {
        ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
            --text "$(echo -e "❌ error try again")" \
            --parse_mode html
        return 0
        _erro='1'
    }
    useradd -M -N -s /bin/false $usuario -e $tuserdate >/dev/null 2>&1
    (
        echo "$senha"
        echo "$senha"
    ) | passwd $usuario >/dev/null 2>&1
    echo "$senha" >/etc/VPSManager/senha/$usuario
    echo "$usuario $limite" >>/root/usuarios.db
    [[ "${message_from_id[$id]}" != "$id_admin" ]] && {
        echo "$usuario:$senha:$ex_date:$limite" >/etc/bot/revenda/${message_from_username}/usuarios/$usuario
    }
    dir_teste="/etc/bot/revenda/${message_from_username}/usuarios/$usuario"
    cat <<-EOF >/etc/VPSManager/userteste/$usuario.sh
	#!/bin/bash
	# USUARIO TESTE
	[[ \$(ps -u "$usuario" | grep -c sshd) != '0' ]] && pkill -u $usuario
	userdel --force $usuario
	grep -v ^$usuario[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
	[[ -e $dir_teste ]] && rm $dir_teste
	rm /etc/VPSManager/senha/$usuario > /dev/null 2>&1
	rm /etc/VPSManager/userteste/$usuario.sh
	EOF
    chmod +x /etc/VPSManager/userteste/$usuario.sh
    echo "/etc/VPSManager/userteste/$usuario.sh" | at now + $t_time hour >/dev/null 2>&1
    [[ "$t_time" == '1' ]] && hrs="hora" || hrs="horas"
    [[ "$(ls /etc/bot/arquivos | wc -l)" != '0' ]] && {
        for arqv in $(ls /etc/bot/arquivos); do
            ShellBot.sendDocument --chat_id ${message_from_id[$id]} \
                --document "@/etc/bot/arquivos/$arqv" \
                --caption "$(echo -e "<b>====================================</b>\n<b>      ❣️ SLEHIBOT VPS MANAGER ❣️</b>\n<b>====================================</b>\n\n<b>❖─────༻ IMPORTANT ༺─────❖</b>\n\n✧⇝ 🚫 NO SPAM\n✧⇝ ⚠️ NO DDOS\n✧⇝ 🎭 NO Hacking\n✧⇝ ⛔️ NO Carding\n✧⇝ 🙅‍♂️ NO Torrent\n✧⇝ ❌ NO MultiLogin\n✧⇝ 🤷‍♂️ NO Illegal Activities\n\n<b>❖─────༻TEST SSH ACCOUNT༺─────❖</b>\n\n<b>✰ Username    ៚</b>  <code>$usuario</code>\n<b>✰ Password     ៚</b> <code>1234</code>\n<b>✰ Expire at  ៚</b> $t_time $hrs / Hours \n\n<b>❖─────༻ PORTS ༺─────❖</b>\n\n⍟ SSH            ⍨   22\n⍟ SSL             ⍨  443\n⍟ Squid         ⍨  8080\n⍟ DropBear ⍨  80\n⍟ BadVPN    ⍨  7300\n\n<b>❖─────༻ SCRIPT MAKE BY ༺─────❖</b>\n<b> ☬── ꧁ SLEHIBOT TEAM ꧂ ──☬ </b>\n<b>❖───── ⍨ ──── ⍤ ──── ⍨ ─────❖</b>\n<b> ☬❦─ ⍣ LAKMAL 〄 SANDARU ⍣ ─❦☬</b>\n<b>❖───── ⍨ ──── ⍤ ──── ⍨ ─────❖</b>")" \
                --parse_mode html
        done
        return 0
    } || {
        ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
            --text "$(echo -e "<b>====================================</b>\n<b>      ❣️ SLEHIBOT VPS MANAGER ❣️</b>\n<b>====================================</b>\n\n<b>❖─────༻ IMPORTANT ༺─────❖</b>\n\n✧⇝ 🚫 NO SPAM\n✧⇝ ⚠️ NO DDOS\n✧⇝ 🎭 NO Hacking\n✧⇝ ⛔️ NO Carding\n✧⇝ 🙅‍♂️ NO Torrent\n✧⇝ ❌ NO MultiLogin\n✧⇝ 🤷‍♂️ NO Illegal Activities\n\n<b>❖─────༻TEST SSH ACCOUNT༺─────❖</b>\n\n<b>✰ Host / IP       ៚</b>  <code>$(cat /etc/IP)</code>\n<b>✰ Username    ៚</b>  <code>$usuario</code>\n<b>✰ Password     ៚</b> <code>1234</code>\n<b>✰ Expire at       ៚</b> $t_time $hrs / Hours \n\n<b>❖─────༻ PORTS ༺─────❖</b>\n\n⍟ SSH            ⍨   22\n⍟ SSL             ⍨  443\n⍟ Squid         ⍨  8080\n⍟ DropBear ⍨  80\n⍟ BadVPN    ⍨  7300\n\n<b>❖─────༻ SCRIPT MAKE BY ༺─────❖</b>\n<b> ☬── ꧁ SLEHIBOT TEAM ꧂ ──☬ </b>\n<b>❖───── ⍨ ──── ⍤ ──── ⍨ ─────❖</b>\n<b> ☬❦─ ⍣ LAKMAL 〄 SANDARU ⍣ ─❦☬</b>\n<b>❖───── ⍨ ──── ⍤ ──── ⍨ ─────❖</b>")" \
            --parse_mode html
        return 0
    }
}
msg_bem_vindo() {
    local msg
    msg="👋 Hello ${message_from_first_name[$id]} ! \n\n🤝 Welcome to\n"
    msg+="<b>================================</b>\n<b>      ❣️ SLEHIBOT VPS MANAGER ❣️   </b>\n<b>================================</b>\n\n"
    msg+="<b>To access the menu</b>\n<b>click [ /menu ]</b>\n\n"
    msg+="<b>For information</b>\n<b>click [ /help ]</b>\n\n ✅ All Tutorials , Updates : @slehiteam"
    ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
        --text "$(echo -e $msg)" \
        --parse_mode html
    ShellBot.sendSticker --chat_id ${message_chat_id[$id]} \
        --sticker "CAACAgIAAxkBAAEDZt1hqPwEyUPLlqUVp27340hwwsO8OAACugADMNSdEYTXxIjEUGdWIgQ"
    return 0
}

# LISTA MENU ADMIN
unset menu1
menu1=''
ShellBot.InlineKeyboardButton --button 'menu1' --line 2 --text 'CREATE TEST' --callback_data '_criarteste'
ShellBot.InlineKeyboardButton --button 'menu1' --line 2 --text 'OTIMIZAR' --callback_data '_otimizar'
ShellBot.InlineKeyboardButton --button 'menu1' --line 5 --text 'SPEEDTEST' --callback_data '_speedteste'
ShellBot.InlineKeyboardButton --button 'menu1' --line 9 --text 'HELP' --callback_data '_ajuda'
ShellBot.regHandleFunction --function fun_add_teste --callback_data _criarteste
ShellBot.regHandleFunction --function otimizer --callback_data _otimizar
ShellBot.regHandleFunction --function speed_test --callback_data _speedteste
fun_menurevenda --callback_data _opcoesrev
unset keyboard1
keyboard1="$(ShellBot.InlineKeyboardMarkup -b 'menu1')"

# LISTA MENU REVENDEDOR
unset menu2
menu2=''
ShellBot.InlineKeyboardButton --button 'menu2' --line 1 --text 'CREATE TEST' --callback_data '_criarteste2'
ShellBot.InlineKeyboardButton --button 'menu2' --line 6 --text 'HELP' --callback_data '_ajuda2'
ShellBot.regHandleFunction --function fun_add_teste --callback_data _criarteste2
ShellBot.regHandleFunction --function fun_ajuda --callback_data _ajuda2
unset keyboard2
keyboard2="$(ShellBot.InlineKeyboardMarkup -b 'menu2')"

#LISTA MUNU SUB REVENDEDOR
unset menu3
menu3=''
ShellBot.InlineKeyboardButton --button 'menu3' --line 1 --text 'CREATE TEST' --callback_data '_criarteste3'
ShellBot.InlineKeyboardButton --button 'menu3' --line 5 --text 'HELP' --callback_data '_ajuda3'
ShellBot.regHandleFunction --function fun_add_teste --callback_data _criarteste3
ShellBot.regHandleFunction --function fun_ajuda --callback_data _ajuda3
unset keyboard3
keyboard3="$(ShellBot.InlineKeyboardMarkup -b 'menu3')"

#LISTA MENU OPCOES REVENDA
unset menu4
menu4=''
unset keyboard4
keyboard4="$(ShellBot.InlineKeyboardMarkup -b 'menu4')"

                    [[ -z $_VAR1 ]] && {
                        ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
                            --text "$(echo -e "❌ Dealer ${message_text[$id]} does not exist")" \
                            --parse_mode html
                        break
                    }
                    susp_rev $_VAR1
                    break
                    ;;
                '🙎‍♂️ CREATE TEST SSH 🙎‍♂️\n\nHow Many Hours Should It Last EX: 1:')
                    verifica_acesso
                    echo $_erro
                    [[ "$_erro" == '1' ]] && break
                    [[ ${message_text[$id]} != ?(+|-)+([0-9]) ]] && {
                        ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
                            --text "$(echo -e "❌ Error ! \n\nuse only numbers [EX: 1]")" \
                            --parse_mode html
                        >$CAD_ARQ
                        break
                    }
                    [[ "${message_from_id[$id]}" != "$id_admin" ]] && {
                        _limTotal=$(grep -w "${message_from_username}" $ativos | awk '{print $4}')
                        fun_verif_limite_rev ${message_from_username}
                        _limsomarev2=$(echo "$_result + 1" | bc)
                        [[ "$_limsomarev2" -gt "$_limTotal" ]] && {
                            ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
                                --text "$(echo -e "❌ you don't have enough limit")" \
                                --parse_mode html
                            >$CAD_ARQ
                            break
                        }
                    }
                    fun_teste ${message_text[$id]}
                    ;;
                esac
            fi
        ) &
    done
done
#FIM
